language: node_js
node_js:
  - stable
script: 
  - npm run test
  - npm run build
  - npm run serve &
  - npm run nightwatch_local
  - npm run test
deploy:
  provider: script
  script: ci/deploy_from_travis.sh
  skip_cleanup: true
  on:
        branch: master

